/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2024-04-17 10:59:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("	\r\n");
      out.write("	<!DOCTYPE html>\r\n");
      out.write("	<html lang=\"en\">\r\n");
      out.write("	<head>\r\n");
      out.write("	    <meta charset=\"UTF-8\">\r\n");
      out.write("	    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("	    <title>Login Page</title>\r\n");
      out.write("	    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	    <style>\r\n");
      out.write("	        .bg-image-vertical {\r\n");
      out.write("	            position: relative;\r\n");
      out.write("	            overflow: hidden;\r\n");
      out.write("	            background-repeat: no-repeat;\r\n");
      out.write("	            background-position: right center;\r\n");
      out.write("	            background-size: auto 50%;\r\n");
      out.write("	        }\r\n");
      out.write("	\r\n");
      out.write("	        @media (min-width: 1025px) {\r\n");
      out.write("	            .h-custom-2 {\r\n");
      out.write("	                height: 50%;\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("	    </style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("	<div class=\"container-fluid mt-3\">\r\n");
      out.write("	</div>\r\n");
      out.write("	<section class=\"vh-100 bg-image-vertical\">\r\n");
      out.write("	    <div class=\"container-fluid\">\r\n");
      out.write("	        <div class=\"row\">\r\n");
      out.write("	            <div class=\"col-sm-6 text-black\">\r\n");
      out.write("	                <div class=\"px-5 ms-xl-4\">\r\n");
      out.write("	                   <span class=\"h1 fw-bold mb-0 text-info animated\">Xin Chào!</span>\r\n");
      out.write("	                </div>        \r\n");
      out.write("	                <div class=\"d-flex align-items-center h-custom-2 px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5\">\r\n");
      out.write("	                    <form id=\"loginForm\" class=\"form-signin\" style=\"width: 23rem\" action=\"Login\" method=\"post\">\r\n");
      out.write("	                        <h3 class=\"fw-normal mb-3 pb-3\" style=\"letter-spacing: 1px;\">Đăng ký</h3>\r\n");
      out.write("	                        <div class=\"form-outline mb-4\">\r\n");
      out.write("	                            <label class=\"form-label\" for=\"form2Example18\">𝙴𝚖𝚊𝚒𝚕 </label>\r\n");
      out.write("	                            <input name=\"email\" type=\"text\" class=\"form-control form-control-lg\" placeholder=\"Email\" required autofocus />\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                        <div class=\"form-outline mb-4\">\r\n");
      out.write("	                            <label class=\"form-label\" for=\"form2Example28\">𝙿𝚊𝚜𝚜𝚠𝚘𝚛𝚍</label>\r\n");
      out.write("	                            <input name=\"password\" type=\"password\" class=\"form-control form-control-lg\" placeholder=\"Password\" required />\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                         ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("	        <div class=\"alert alert-danger\" role=\"alert\">\r\n");
      out.write("	            ");
      out.print( request.getAttribute("error") );
      out.write("\r\n");
      out.write("	        </div>\r\n");
      out.write("	    ");
 } 
      out.write("\r\n");
      out.write("	                        <div class=\"pt-1 mb-4\">\r\n");
      out.write("	                            <button class=\"btn btn-success btn-block\" type=\"submit\">Đăng Nhập</button>                           \r\n");
      out.write("	                            <p>Don't have an account? <a href=\"Register\" class=\"link-info\">Đăng Kí Ngay</a>\r\n");
      out.write("	</p>\r\n");
      out.write("	                        </div>\r\n");
      out.write("	                    </form>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"col-sm-6 px-0 d-none d-sm-block\">\r\n");
      out.write("	                <img src=\"https://isetups.vn/wp-content/uploads/2021/09/1-2-scaled.jpg\"\r\n");
      out.write("	                    alt=\"Login image\" class=\"w-100 vh-100\" style=\"object-fit: cover; object-position: left;\">\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	</body>\r\n");
      out.write("	</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
